language: node_js

node_js:
  - 12.18.3

notifications:
  email:
    recipients:
      - dengguiheng@vikadata.com
      - dev@vikadata.com
    on_success: change
    on_failure: always

env:
  global:
    - secure: EYKE8OVD7GA+QyBDi0857Kjz4QxIwd3nOuau6VB+Egho3h+w4ElQ+j7Qbn4DPcrdEWzJfxXFp8MtGPoKoDiGKZUGVZa+qzL8/ttMy6s70JYnzs7D98Ce/tYgV76gn2ClxlrAciHxAZkjxwIYpr5qTnXHrsEIH4N6ibv6UPxZ5N6RrxkS7Wkd+WOiPYBKidE2H/TPMKq1rr3aqfVZ7ucI5DikTGnMHoVpKVVPGnF5SYcYcOXoBUG/ANvbjom3UNTDEUfqqfte0nKkRxOfVzUyBYoppPtK0sW7PA1k6KwJwFjprK+LBf6oOmcDJRXbZH+lnC8nhtZ3VCl7YSBzZhoio7YpBMA+/dNT4UD4bw+FyQ0dt7phXNQETiaLE1u2iz+NuxinYvbzCMgsgNs2WwTbFBOFBAN01J4oeqFuGW8XFbqTJJiMML3K5cHNUdXFmiqw/uR6r3FYdR/95b5qTVU+Dfyqq/0ZFAYcUvUd9vIk9v2c63YXzr4O0+ZVhkr11cTycpYGQbcUk1clJT+h9VTyUlbPPyo79SxV11CHS4b+W94dE148i9Op9+zReLGK1asyCOXGGUIjreF2y5Pfg18FrzS56dj1ZUv207iWBJ55O3r8Cp4i67vy7DaaML3cIhbrQfwHI8s3p+5nCh45JBSUWwadNhMDcxzc4fXPckqaVGI=
    - secure: SOKxGWbGLwAZI2oS7DYNAPVaq8HBgLE8w5OGD8izsV2kzPZ8EgeZUx/v4G3Z9+Ti1vKNDugt76/tWVwFNU1aPBZzMUsSaTcfc9eZbTqlofnsGfF1hGhJNmNlDDJfUZyuj4zCm5r+mQrZu/coYIAcH9ycKB300wdFoEBXQed6k4mEnr3WycuBrS25nvuXxzLT6pMP5EPMB+xo0DSYnN4x2ZC1zgP7nJ1H1mJbMiWn4GcBMSxherfLn7RG/HW4O91LZRIStFNKojMT+mCkm4DFSCFZhCPEaJ+GB+wQuLJREKYGUUhjrowt+ImxSHGdV0RP1NCqsV7HBb8LP+GvsD5ggAjBgaB9QxzgH7yW+LzpkS7HrIa3fjtfMZd/tm6TPjEgJ24dlPqKinydlT0F5KE0uQ/pTvcZkHwzpT/W48QZpgWCwO28LiyKaASlzs0YlmpEDDGbhIhvjVTa2F1p5koDVl0SJ+Pgze3Ju3obiKR0PrGqUqlcmJjmMIllcJoN/n7XiuffdOcKlh5+efnP9wtzzA7wjTVw02qfKjnnITMCl3/jyQtMihc1L1DHgRCN+TrVY6j4eV3RFLx0oiM2QVM1bHvsfKBUrxe8w6vm1W95svBhKCPWI38Z6wFcPUX9nqO+P2cWuO50sKc1QmGPeub21dYQinJGi8vC9OeBHuImg00=

script:
  - echo "skip test"

deploy:
  - skip_cleanup: true
    provider: script
    script: bash .ci/publish.sh
    on:
      branch: devops