# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Codecov CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - env:
          VIKA_API_TOKEN: ${{ env.VIKA_API_TOKEN }}
          VIKA_API_DATASHEET: ${{ env.VIKA_API_DATASHEET }}
      - run: yarn
      - run: yarn test:coverage
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov
