# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Codecov CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: set up env
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'yarn'
      - name: test and upload to codecov
        env:
          VIKA_API_TOKEN: ${{ secrets.VIKA_API_TOKEN }}
          VIKA_API_DATASHEET: ${{ secrets.VIKA_API_DATASHEET }}
        run: |
          yarn
          yarn test:coverage
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

